remote_theme : mmistakes/minimal-mistakes

url                      : "https://passionsjin.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"

locale                   : "en-US"
title                    : "Site Title-Test"
title_separator          : "-??"
name                     : "Park"
description              : "An amazing website. is?"
